server:
    port: 8080
    context-path: /knowbook_prod

spring:
  datasource:
    url: jdbc:mysql://47.93.248.201:3306/knowbook?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: only
    password: 123456
