server:
    port: 8081
    servlet:
          context-path: /knowbook_dev


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/knowbook?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    elasticsearch:
      repositories:
        enable: true
      local: true

      properties:
        path:
         logs: ./elasticsearch/logs
         data: ./elasticsearch/data