server:
    port: 8081
    context-path: /knowbook_dev


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/kownbook?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
