server:
    port: 8080
    context-path: /knowbook_prod

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/knowbook?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
