spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.excellent.knowbookcommon.model.pojo
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true



