server:
    port: 8081
    context-path: /knowbook_dev


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/knowbook?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

#spring:
  data:
      elasticsearch:
#        集群名
#       cluster-name: master
#        连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！ 逗号分隔，如果没有指定，则启动ClientNode
#       cluster-nodes: 127.0.0.1:9300
       properties:
          path:
            logs: ./elasticsearch-5.6.1/logs
            data: ./elasticsearch-5.6.1/data
#        是否本地连接
       local: false
       repositories:
         # 仓库中数据存储
         enabled: true


